---
- name: Ensure admin user exists
  user:
    comment: Admin
    createhome: yes
    home: /ebs/home/admin
    name: admin
    shell: /bin/bash
    state: present

- name: Ensure the admin user is passwordless sudoer
  copy:
    dest: /etc/sudoers.d/admin-user
    content: 'admin ALL=(ALL) NOPASSWD:ALL'
    mode: 0440
    validate: '/usr/sbin/visudo -cf %s'

- name: Ensure the admin user accepts the SSH key
  authorized_key:
    user: admin
    key: "{{ lookup('file', hostvars[inventory_hostname].admin_public_key | mandatory ) }}"
    state: present
