---
- name: Format EBS volume
  become: yes
  filesystem:
    dev: "{{ ebs }}"
    fstype: ext4

- name: Create mounting point
  become: yes
  file:
    path: /ebs/home
    state: directory
    mode: 0755

- name: Mount EBS home
  become: yes
  mount:
    fstype: ext4
    path: /ebs/home
    src: "{{ ebs }}"
    state: mounted
